---
- hosts: localhost
  collections:
    - my_own_namespace.yandex_cloud_elk

  tasks:
    - import_role:
        name: role_for_module

    - my_own_module:
        path: /root/tmp.txt
        content: 234